// <auto-generated />
namespace TcUnip.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Inclusao_Relacionamento_Caxa_x_Sessao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inclusao_Relacionamento_Caxa_x_Sessao));
        
        string IMigrationMetadata.Id
        {
            get { return "201812012016468_Inclusao_Relacionamento_Caxa_x_Sessao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
